apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-test
  template:
    metadata:
      labels:
        app: echo-test
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args:
          - "-text=Â¡Hola desde Kubernetes!"
        ports:
        - containerPort: 5678
        envFrom:
          - secretRef:
            name: openai-secret
